# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from protos.sibur.iiot import iiot_device_pb2 as protos_dot_sibur_dot_iiot_dot_iiot__device__pb2


class IotDeviceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getDeviceList = channel.unary_unary(
        '/protos.sibur.iiot.IotDevice/getDeviceList',
        request_serializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceListRequest.SerializeToString,
        response_deserializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceListResponse.FromString,
        )
    self.getDeviceInfo = channel.unary_unary(
        '/protos.sibur.iiot.IotDevice/getDeviceInfo',
        request_serializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceDataRequest.SerializeToString,
        response_deserializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceDataResponse.FromString,
        )
    self.getDeviceHistory = channel.unary_unary(
        '/protos.sibur.iiot.IotDevice/getDeviceHistory',
        request_serializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceHistoryRequest.SerializeToString,
        response_deserializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceHistoryResponse.FromString,
        )
    self.createDevice = channel.unary_unary(
        '/protos.sibur.iiot.IotDevice/createDevice',
        request_serializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.CreateDeviceRequest.SerializeToString,
        response_deserializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.CreateDeviceResponse.FromString,
        )
    self.deleteDevice = channel.unary_unary(
        '/protos.sibur.iiot.IotDevice/deleteDevice',
        request_serializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeleteDeviceRequest.SerializeToString,
        response_deserializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeleteDeviceResponse.FromString,
        )
    self.updateDevice = channel.unary_unary(
        '/protos.sibur.iiot.IotDevice/updateDevice',
        request_serializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.UpdateDeviceRequest.SerializeToString,
        response_deserializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.UpdateDeviceResponse.FromString,
        )
    self.sendDeviceConfiguration = channel.unary_unary(
        '/protos.sibur.iiot.IotDevice/sendDeviceConfiguration',
        request_serializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceConfigurationRequest.SerializeToString,
        response_deserializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceConfigurationResponse.FromString,
        )


class IotDeviceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getDeviceList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getDeviceInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getDeviceHistory(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def createDevice(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def deleteDevice(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def updateDevice(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def sendDeviceConfiguration(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_IotDeviceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getDeviceList': grpc.unary_unary_rpc_method_handler(
          servicer.getDeviceList,
          request_deserializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceListRequest.FromString,
          response_serializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceListResponse.SerializeToString,
      ),
      'getDeviceInfo': grpc.unary_unary_rpc_method_handler(
          servicer.getDeviceInfo,
          request_deserializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceDataRequest.FromString,
          response_serializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceDataResponse.SerializeToString,
      ),
      'getDeviceHistory': grpc.unary_unary_rpc_method_handler(
          servicer.getDeviceHistory,
          request_deserializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceHistoryRequest.FromString,
          response_serializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceHistoryResponse.SerializeToString,
      ),
      'createDevice': grpc.unary_unary_rpc_method_handler(
          servicer.createDevice,
          request_deserializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.CreateDeviceRequest.FromString,
          response_serializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.CreateDeviceResponse.SerializeToString,
      ),
      'deleteDevice': grpc.unary_unary_rpc_method_handler(
          servicer.deleteDevice,
          request_deserializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeleteDeviceRequest.FromString,
          response_serializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeleteDeviceResponse.SerializeToString,
      ),
      'updateDevice': grpc.unary_unary_rpc_method_handler(
          servicer.updateDevice,
          request_deserializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.UpdateDeviceRequest.FromString,
          response_serializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.UpdateDeviceResponse.SerializeToString,
      ),
      'sendDeviceConfiguration': grpc.unary_unary_rpc_method_handler(
          servicer.sendDeviceConfiguration,
          request_deserializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceConfigurationRequest.FromString,
          response_serializer=protos_dot_sibur_dot_iiot_dot_iiot__device__pb2.DeviceConfigurationResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protos.sibur.iiot.IotDevice', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
